#!/bin/bash
no_proxy=ip.sb
auth_key=""
zone_name="example.com"
record_name="example.example.com"
record_type="AAAA"
ip_index="internet" #internet or local
eth_card="eth0"
ip_file="ip.txt"

if [ $record_type = "AAAA" ]; then
    if [ $ip_index = "internet" ]; then
        ip=$(curl -s -6 ip.sb)
    elif [ $ip_index = "local" ]; then
        if [ "$user" = "root" ]; then
            ip=$(ifconfig $eth_card | grep 'inet6' | grep -v '::1' | grep -v 'fe80' | cut -f2 | awk '{ print $2}' | head -1)
        else
            ip=$(/sbin/ifconfig $eth_card | grep 'inet6' | grep -v '::1' | grep -v 'fe80' | cut -f2 | awk '{ print $2}' | head -1)
        fi
    else
        echo "Error IP index, please input the right type"
        exit 0
    fi
elif [ $record_type = "A" ]; then
    if [ $ip_index = "internet" ]; then
        ip=$(curl -s -4 ip.sb)
    elif [ $ip_index = "local" ]; then
        if [ "$user" = "root" ]; then
            ip=$(ifconfig $eth_card | grep 'inet' | grep -v '127.0.0.1' | grep -v 'inet6' | cut -f2 | awk '{ print $2}')
        else
            ip=$(/sbin/ifconfig $eth_card | grep 'inet' | grep -v '127.0.0.1' | grep -v 'inet6' | cut -f2 | awk '{ print $2}')
        fi
    else
        echo "Error IP index, please input the right type"
        exit 0
    fi
else
    echo "Error DNS type"
    exit 0
fi

if [ -f $ip_file ]; then
    old_ip=$(cat $ip_file)
    if [ $ip == $old_ip ]; then
        echo "IP has not changed."
        exit 0
    fi
fi

zone_identifier=$(
    curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$zone_name" \
        -H "Authorization: Bearer $auth_key" \
        -H "content-type: application/json" | grep -Po '(?<="id":")[^"]*' | head -1
)
record_identifier=$(
    curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records?type=${record_type}&name=$record_name" \
        -H "Authorization: Bearer $auth_key" \
        -H "Content-Type: application/json" | grep -Po '(?<="id":")[^"]*'
)

update=$(
    curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records/$record_identifier" \
        -H "Authorization: Bearer $auth_key" \
        -H "Content-Type: application/json" \
        --data "{\"type\":\"$record_type\",\"name\":\"$record_name\",\"content\":\"$ip\",\"ttl\":1,\"proxied\":false}"
)

if [[ $update == *"\"success\":true"* ]]; then
    message="IP changed to: $ip"
    echo "$ip" >$ip_file
    echo "$message"
else
    message="API UPDATE FAILED. DUMPING RESULTS:\n$update"
    echo -e "$message"
    exit 1
fi
